# This file can be used to install module dependencies for unit testing
# See https://github.com/puppetlabs/puppetlabs_spec_helper#using-fixtures for details
---
fixtures:
  forge_modules:
    stdlib: "puppetlabs/stdlib"
    concat: "puppetlabs/concat"
    postgresql: "puppetlabs/postgresql"
    puppetdb: "puppetlabs/puppetdb"
    puppet_metrics_dashboard: "puppetlabs/puppet_metrics_dashboard"
    puppet_metrics_collector: "puppetlabs/puppet_metrics_collector"
    nfs: "derdanne/nfs"
    yumrepo: "puppetlabs/yumrepo_core"
    grafana: "puppet/grafana"
    telegraf: "puppet/telegraf"
    puppetserver_gem: "puppetlabs/puppetserver_gem"
  repositories:
    facts: 'git://github.com/puppetlabs/puppetlabs-facts.git'
    puppet_agent: 'git://github.com/puppetlabs/puppetlabs-puppet_agent.git'
    provision: 'git://github.com/puppetlabs/provision.git'
